In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#gestion de nulos 
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

In [6]:
df = pd.read_csv("files/Lifestyle_and_Health_Risk_Prediction_Synthetic_Dataset.csv")
df.head()

,age,weight,height,exercise,sleep,sugar_intake,smoking,alcohol,married,profession,bmi,health_risk
0,56,67,195,low,6.1,medium,yes,yes,yes,office_worker,17.6,high
1,69,76,170,high,6.9,high,no,no,no,teacher,26.3,high
2,46,106,153,high,6.6,low,yes,no,no,artist,45.3,high
3,32,54,186,medium,8.5,medium,no,no,no,artist,15.6,low
4,60,98,195,high,8.0,low,no,no,yes,teacher,25.8,high

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           5000 non-null   int64
 1   weight        5000 non-null   int64
 2   height        5000 non-null   int64
 3   exercise      5000 non-null   str
 4   sleep         5000 non-null   float64
 5   sugar_intake  5000 non-null   str
 6   smoking       5000 non-null   str
 7   alcohol       5000 non-null   str
 8   married       5000 non-null   str
 9   profession    5000 non-null   str
 10  bmi           5000 non-null   float64
 11  health_risk   5000 non-null   str
dtypes: float64(2), int64(3), str(7)
memory usage: 468.9 KB

In [22]:
df.shape

(5000, 12)

- Duplicados

In [19]:
df.duplicated().sum()

np.int64(0)

- Nulos

In [21]:
round(df.isnull().sum()/df.shape[0]*100, 2)

age             0.0
weight          0.0
height          0.0
exercise        0.0
sleep           0.0
sugar_intake    0.0
smoking         0.0
alcohol         0.0
married         0.0
profession      0.0
bmi             0.0
health_risk     0.0
dtype: float64

- Valores únicos de cada columna

In [24]:
df["exercise"].value_counts()

exercise
medium    1985
low       1272
high      1000
none       743
Name: count, dtype: int64

In [25]:
df["sleep"].value_counts()

sleep
6.8    140
6.6    136
7.0    136
7.1    136
7.4    133
      ...
3.5     10
3.4      9
3.1      5
3.3      4
3.2      2
Name: count, Length: 71, dtype: int64

In [26]:
df["sugar_intake"].value_counts()

sugar_intake
medium    2511
low       1484
high      1005
Name: count, dtype: int64

In [27]:
df["smoking"].value_counts()

smoking
no     4023
yes     977
Name: count, dtype: int64

In [28]:
df["alcohol"].value_counts()

alcohol
no     3741
yes    1259
Name: count, dtype: int64

In [12]:
df["married"].value_counts()

married
yes    3018
no     1982
Name: count, dtype: int64

In [14]:
df["profession"].value_counts()

profession
student          644
farmer           639
driver           631
doctor           630
artist           626
engineer         616
teacher          612
office_worker    602
Name: count, dtype: int64

In [29]:
df["bmi"].value_counts()

bmi
26.0    46
28.7    43
26.3    38
29.4    35
32.0    34
        ..
51.4     1
44.8     1
11.4     1
11.8     1
50.7     1
Name: count, Length: 383, dtype: int64

In [30]:
df["health_risk"].value_counts()

health_risk
high    3490
low     1510
Name: count, dtype: int64

- Variables numericas

In [32]:
df.describe().T

         count       mean        std    min    25%    50%    75%    max
age     5000.0   48.80560  17.906991   18.0   34.0   49.0   64.0   79.0
weight  5000.0   77.35920  18.714567   45.0   61.0   77.0   94.0  109.0
height  5000.0  171.93320  15.822225  145.0  158.0  171.5  186.0  199.0
sleep   5000.0    6.99706   1.432849    3.0    6.0    7.0    8.0   10.0
bmi     5000.0   26.84388   8.252490   11.4   20.3   26.0   32.4   51.4

- Variables categoricas

In [40]:
df.describe(include="object").T

C:\Users\Personal\AppData\Local\Temp\ipykernel_25004\1274302342.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object").T

             count unique      top  freq
exercise      5000      4   medium  1985
sugar_intake  5000      3   medium  2511
smoking       5000      2       no  4023
alcohol       5000      2       no  3741
married       5000      2      yes  3018
profession    5000      8  student   644
health_risk   5000      2     high  3490