In [20]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df = pd.read_csv("files/comida_precios.csv")
df.head()

         Alimento  Tipo  Precio_EUR_kg_L   Sueño  Energia
0    Pollo fresco  Real              6.0  Neutro        8
1          Salmón  Real             10.0   Bueno        9
2          Huevos  Real              3.0   Bueno        8
3           Avena  Real              2.0   Bueno        7
4  Arroz integral  Real              2.2  Neutro        7

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Alimento         71 non-null     str
 1   Tipo             71 non-null     str
 2   Precio_EUR_kg_L  71 non-null     float64
 3   Sueño            71 non-null     str
 4   Energia          71 non-null     int64
dtypes: float64(1), int64(1), str(3)
memory usage: 2.9 KB

Hemos detectado que no existen nulos, ni duplicados en el df. El tipo de dato esta correcto

In [23]:
df.columns

Index(['Alimento', 'Tipo', 'Precio_EUR_kg_L', 'Sueño', 'Energia'], dtype='str')

In [24]:
df.shape

(71, 5)

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df['Tipo'].value_counts(normalize=True)*100

Tipo
Real     57.746479
Ultra    42.253521
Name: proportion, dtype: float64

In [27]:
df['Sueño'].value_counts(normalize=True)*100

Sueño
Malo      42.253521
Neutro    29.577465
Bueno     28.169014
Name: proportion, dtype: float64

In [28]:
df.drop(columns="Energia", inplace=True)

In [29]:
df.sample()

        Alimento  Tipo  Precio_EUR_kg_L   Sueño
19  Aceite oliva  Real              8.5  Neutro

In [30]:
df.describe(include=np.number).T

                 count      mean       std  min  25%  50%  75%   max
Precio_EUR_kg_L   71.0  3.514085  2.677915  0.5  2.0  2.6  4.0  15.0

In [31]:
df.describe(include=str).T

         count unique           top freq
Alimento    71     71  Pollo fresco    1
Tipo        71      2          Real   41
Sueño       71      3          Malo   30